services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  backend:
    build: ./backend
    ports: ["8000:8000"]
    depends_on: [redis]
    env_file: ./backend/.env
    environment:
      DATABASE_URL: postgresql://nutri_user:secret@host.docker.internal/nutrisuggest_db
      REDIS_URL: redis://redis:6379/0

  celery:
    build: ./backend
    command: celery -A app.workers.celery_app worker --loglevel=info
    depends_on: [redis]
    env_file: ./backend/.env
    environment:
      DATABASE_URL: postgresql://nutri_user:secret@host.docker.internal/nutrisuggest_db
      REDIS_URL: redis://redis:6379/0

  # frontend:
  #   build: ./frontend
  #   ports: ["3000:3000"]
  #   environment:
  #     NEXT_PUBLIC_API_URL: http://localhost:8000/api/v1
